package fallas;

import Puesto;
import Operador;
import Ambiente;

dialect  "mvel"

// Regla 1 "Verificar protección personal"
//SI el operario no tiene zapatos de seguridad, no tiene ropa de trabajo o la tiene pero ésta tiene mas de 6 meses de antiguedad, no posee protección visual o no posee protección auditiva ENTONCES el puesto de trabajo no cumple con normas de protección personal.
//Formulación externa de la regla
// SI   (zapatos_de_seguridad=No)
//      ó ((ropa_de_trabajo=No) ó ((ropa_de_trabajo=Si) y (antiguedad>6 meses)))
//      ó ((protección_visual=No) ó ((nivel_de_ruido>85 db) y (protección_auditiva=No))
//ENTONCES resultado=el puesto de trabajo no cumple con normas de protección personal.
rule "ProteccionPersonal_NoAuditiva"
salience 100
    when
    puesto : Puesto( );
    op: Operador(!zapatosDeSeguridad ||
    (!ropaDeTrabajo || (ropaDeTrabajo && antiguedad > 6))) from puesto.getOperador();
    p : Operador(!zapatosDeSeguridad && !protecciónAuditiva) Ambiente(nivelRuido > 85) from puesto;
    then
    puesto.setOperadorAprobado(false);
end


// Regla 2 "Verificar higiene en el ambiente laboral"
//SI el ambiente de trabajo supera el umbral de ruido permitido, (85db), tiene un nivel de iluminación menor a 300 lux o no está debidamente delimitada ENTONCES el puesto de trabajo no cumple de higiene en el ambientes laboral.
//Formulación externa de
//la regla
//SI ((nivel_de_ruido>85 db) y (protección_auditiva=No))
//   ó (nivel_de_luz<300 lux) ó (delimitación=No)
//ENTONCES resultado=el puesto de trabajo no cumple con normas de higiene en el ambientes laboral.
rule "HigieneAmbiente"
    salience 99
    when
        puesto : Puesto();
        ambiente1 : Ambiente(nivelRuido < 85) from puesto.getAmbiente();
        ambiente2 : Ambiente(nivelLuz >= 300) from puesto.getAmbiente();
        ambiente3 : Ambiente(delimitacion == true) from puesto.getAmbiente();
    then
        puesto.setAmbienteAprobado(true);
end

// Cancelan tanto Regla 1 como Regla 2
rule "ProteccionAuditiva"
    salience 98
    when
        puesto : Puesto();
        op : Operador(protecciónAuditiva == false) from puesto.getOperador();
        ambiente : Ambiente(nivelRuido > 85.0) from puesto.getAmbiente();
    then
        puesto.setOperadorAprobado(false);
        puesto.setAmbienteAprobado(false);
end

// Regla 3
//Estado de la regla
//SI la maquina guillotina no tiene descarga a tierra o no tiene protección de riesgo mecánico (delimitación de zona de riesgo, sensores de detección, panel delimitador de acceso de manos o comando de acción a dos manos) ENTONCES el puesto de trabajo no cumple con normas de seguridad en el ambiente laboral.
//Formulación externa de
//la regla
//SI (descarga_a_tierra=No) ó ((delimitación_de_zona_de_riego=No) y (sensores_de_detección=No) y (panel_delimitador_de_acceso=No) y (comando_de_acción_a_dos_manos=No)) ENTONCES resultado=el puesto de trabajo no cumple con normas de seguridad en el ambiente laboral.
//Nombre de la regla
//Verificar seguridad en el ambiente laboral.

// Regla 4
//Estado de la regla
//SI el operario tiene zapatos de seguridad, tiene ropa de trabajo y ésta tiene menos de 6 meses de antigüedad, posee protección visual, posee protección auditiva, además el ambiente de trabajo no supera el umbral de ruido permitido, (85db), tiene un nivel de iluminación superior a 300 lux, está debidamente delimitada y, la máquina guillotina tiene descarga a tierra y protección de riesgo mecánico (delimitación de zona de riesgo, sensores de detección, panel delimitador de acceso de manos o comando de acción a dos manos)  ENTONCES el puesto de trabajo cumple con las normas de seguridad e higiene para el mismo.
//Formulación externa de
//la regla
//SI (zapatos_de_seguridad=Si) y ((ropa_de_trabajo=Si) y (antiguedad<6 meses)) y ((protección_visual=Si) ó (nivel_de_ruido<85 db)) y (nivel_de_luz>=300 lux) y (delimitación=Si) y (descarga_a_tierra=Si) y ((delimitación_de_zona_de_riego=Si) ó (sensores_de_detección=Si) ó (panel_delimitador_de_acceso=Si) ó (comando_de_acción_a_dos_manos=Si)) ENTONCES resultado=el puesto de trabajo cumple con las normas de seguridad e higiene para el mismo.
//Nombre de la regla
//Puesto de trabajo seguro e higiénico.
